apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: egress-gateway
spec:
  host: egress-gateway.istio-system.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
